# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /springbootpavyhdan


spring:
    datasource:
      url: jdbc:mysql://192.168.232.128:3306/springbootpavyhdan?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
        #        mysql 8.0
        #        driver-class-name: com.mysql.cj.jdbc.Driver

        #        mysql5.7
      driver-class-name: com.mysql.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 300MB
        max-request-size: 300MB
    resources:
      static-locations: classpath:static/,file:static/

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.entity

